version: '3'

services:
  app:
    image: 'boilerplate-mern'
    build:
      context: .
      dockerfile: Dockerfile
      args:
        NODE_ENV: 'development'
    environment:
      NODE_APP_INSTANCE: 'docker'
    command: sh -c 'mkdir -p /opt/app/.nyc_output && npm run coverage:export'
    depends_on:
      - db
    volumes:
      - .:/opt/app

  db:
    image: mongo:5.0
    command: mongod --quiet --logpath /dev/null
    ports:
      - '27017:27017'
