ingress:
  enabled: true
  hosts:
    - "${docker_registry}"
  annotations:
    cert-manager.io/cluster-issuer: "${cluster_issuer_name}"
    nginx.ingress.kubernetes.io/proxy-body-size: "30720m"
  tls:
    - secretName: docker-registry-prod
      hosts:
        - "${docker_registry}"

secrets:
  htpasswd: "${docker_username}:${docker_hashed_password}"
