accounts:
  tokenKey: 'e2e_auth_token'

documentation:
  enabled: false

mongoDb:
  uri: 'mongodb://localhost:27017/boilerplate-mern-e2e'

openai:
  apiKey: 'OPENAI_API_KEY'

webAppHost: 'http://localhost:8080'
