const styles = {
  alignSelf: {
    auto: 'self-auto',
    baseline: 'self-baseline',
    center: 'self-center',
    flexEnd: 'self-end',
    flexStart: 'self-start',
    stretch: 'self-stretch',
  },
  flex: {
    flex1: 'flex-1',
    flexAuto: 'flex-auto',
    flexInitial: 'flex-initial',
    flexNone: 'flex-none',
    grow: 'grow',
    grow0: 'grow-0',
    shrink: 'shrink',
    shrink0: 'shrink-0',
  },
  justifySelf: {
    auto: 'justify-self-auto',
    center: 'justify-self-center',
    end: 'justify-self-end',
    start: 'justify-self-start',
    stretch: 'justify-self-stretch',
  },
  order: {
    first: 'order-first',
    last: 'order-last',
    none: 'order-none',
    1: 'order-1',
    2: 'order-2',
    3: 'order-3',
    4: 'order-4',
    5: 'order-5',
    6: 'order-6',
    7: 'order-7',
    8: 'order-8',
    9: 'order-9',
    10: 'order-10',
    11: 'order-11',
    12: 'order-12',
  },
};

export default styles;
