name: analysis:sonarqube:pull-request

on:
  # Trigger analysis when creating / updating pull requests
  pull_request:
      types: [opened, synchronize, reopened]

jobs:
  analysis:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
      with:
        # Disabling shallow clone is recommended for improving relevancy of reporting
        fetch-depth: 0

    - name: sonarqube-scan-branch
      uses: sonarsource/sonarqube-scan-action@master
      with:
        args: >
          -Dsonar.pullrequest.key=${{ github.event.number }}
          -Dsonar.pullrequest.branch=${{ github.event.pull_request.head.ref }}
          -Dsonar.pullrequest.base=${{ github.event.pull_request.base.ref }}
      env:
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}
